### ISSUE TITLE
[docker-misp]Proxy doesn't work

### ISSUE THREAD

**Issue by young2112129** [MISP/docker-misp#6]
Thank you for your awesome work on harvarditsecurity/misp.
I have clone it from github and built my own container with the modification of build.sh.

Unfortunately, I have a problem when fetch feed through proxy.
I can see the proxy information in app/Config/config.php.
When I check servers/serverSettings/diagnostics, it shows:

Proxy
This tool tests whether your HTTP proxy settings are correct.
Proxy settings…OK

I try to capture the packets with tcpdump, but there has no traffic sent to proxy(all packets are sent to the feed server directly).
It seems that the proxy configuration didn't work.

Have you ever have this problem?
Do you know how to fix it?

Thank you again and waiting for your feedback.

**Comment by ventz** [comment]
@young2112129 Unfortunately I am not familiar with the proxy setting and I have not used it.

It may be worth opening the question to the MISP community since I don't believe this would be a docker container issue.

Have you looked at this older issue about the proxy by the way:
https://github.com/MISP/MISP/issues/1935
